// Generated by CoffeeScript 1.11.1
var ReactType, Section, emptyFunction, type;

emptyFunction = require("emptyFunction");

ReactType = require("modx/lib/Type");

Section = require("./Section");

type = ReactType("Scrollable_RootSection");

type.inherits(Section);

type.defineOptions({
  scroll: Object.Kind
});

type.defineValues(function(options) {
  return {
    _scroll: options.scroll
  };
});

type.initInstance(function() {
  this._index = 0;
  return this._trackMounting();
});

type.overrideMethods({
  __lengthDidChange: function(length) {
    this._scroll._setContentLength(length);
    this.__super(arguments);
  },
  __getVisibleArea: function() {
    var scroll;
    scroll = this._scroll;
    return {
      startOffset: scroll.offset,
      endOffset: scroll.offset + scroll.visibleLength
    };
  },
  __onRemoveAll: function() {
    this._scroll._setContentLength(null);
  },
  __renderEmpty: function() {
    return this._scroll.__renderEmpty();
  },
  __renderHeader: function() {
    return this._scroll.__renderHeader();
  },
  __renderFooter: function() {
    return this._scroll.__renderFooter();
  },
  __renderOverlay: function() {
    return this._scroll.__renderOverlay();
  },
  __childWillAttach: function(child, index) {
    return this._scroll.__childWillAttach(child, index);
  },
  __childDidAttach: function(child) {
    this._scroll.__childDidAttach(child);
  },
  __childWillDetach: function(child) {
    this._scroll.__childWillDetach(child);
  },
  __childWillMount: function(child) {
    this._scroll.__childWillMount(child);
  },
  __childDidLayout: function(child, lengthChange) {
    this._setLength(this._length + lengthChange);
    this._scroll.__childDidLayout(child, lengthChange);
  },
  __childDidReveal: function(child) {
    this._scroll.__childDidReveal(child);
  },
  __childDidConceal: function(child) {
    this._scroll.__childDidConceal(child);
  }
});

module.exports = type.build();
