// Generated by CoffeeScript 1.11.1
var Element, ReactType, ScrollChild, View, emptyFunction, type;

Element = require("react-validators").Element;

emptyFunction = require("emptyFunction");

ReactType = require("modx/lib/Type");

View = require("modx/lib/View");

ScrollChild = require("./Child");

type = ReactType("Scrollable_Row");

type.inherits(ScrollChild);

type.defineOptions({
  key: String,
  props: Object,
  render: Function.Kind,
  element: Element
});

type.defineValues(function(options) {
  return {
    key: options.key,
    _props: options.props,
    _render: options.render,
    _element: options.element
  };
});

type.defineValues({
  __renderContents: function() {
    if (this._element) {
      return function() {
        return this._element;
      };
    } else if (this._render) {
      return function() {
        return this._render(this._props);
      };
    }
  }
});

type.defineBoundMethods({
  _rootDidLayout: function(event) {
    var layout, newLength, oldLength;
    layout = event.nativeEvent.layout;
    newLength = layout[this.scroll.isHorizontal ? "width" : "height"];
    if (newLength === (oldLength = this._length)) {
      return;
    }
    this._setLength(newLength);
    this._section.__childDidLayout(this, newLength - oldLength);
    this._didLayout.emit();
  }
});

type.render(function() {
  return View({
    ref: this._rootDidRef,
    style: [this.styles.container(), this._rootStyle],
    children: this.__renderContents(),
    onLayout: this._rootDidLayout
  });
});

type.willMount(function() {
  return this.props.row = this;
});

type.willReceiveProps(function(props) {
  return props.row = this;
});

type.defineHooks({
  __renderContents: emptyFunction.thatReturnsFalse
});

type.defineStyles({
  container: {
    overflow: "hidden"
  }
});

module.exports = type.build();
